### ISSUE TITLE
Logback config should not be statically included in jars

### ISSUE THREAD

**Issue by PHameete** [MSG134/IVCT_Framework#101]
The Logback config contains hostname/port and user/password properties on the JMS server. Because we need to have the possibility to change these properties we should make these properties configurable.

Possible solutions:

- Configure a properties or conf folder for such files, next to the bin and lib folder in the distribution. 
- Make these properties dynamically configurable via cmd line parameters or ENV variables.

Preferably in both cases there should be default values suitable for local development, with a possibility to override for deployments.

**Comment by rhzg** [comment]
This should be done by making a local copy of the logback config file. We need to check if this local file can be used to overwrite the version included in the jar file.

Another option could be to configure the gradle distribution task. This need to be investigated

**Comment by ducana** [comment]
Changed the gradle logic so that the logback.config is copied from a testsuite conf directory into the IVCT_Runtime testsuite/lib directory. This lib directory is added to the java classpath so that the logback.config file is found as a resource.
