### ISSUE TITLE
LogSink JMSLogSink has localhost activemq hardcoded in constructor

### ISSUE THREAD

**Issue by PHameete** [MSG134/IVCT_Framework#102]
ActiveMQ hostname is hardcoded in JMSLogSink constructor. Should be configurable in another way. Preferably ENV variable, with a default to localhost if no ENV variable set for development purposes.

**Comment by PHameete** [comment]
Could be solved together with #103 

If the LogSink project will get config that tells it what the JMS service is to use, then this config can also be used to fill in this currently hardcoded host.

**Comment by rhzg** [comment]
we will use env variable ACTIVEMQ_HOST and ACTIVEMQ_PORT

**Comment by ducana** [comment]
Fixed this by using getenv for the global environment variables: ACTIVEMQ_HOST and ACTIVEMQ_PORT. The default values are "localhost" and "61616" respectively.
