### ISSUE TITLE
LogSink depends on the IVCT.properties

### ISSUE THREAD

**Issue by PHameete** [MSG134/IVCT_Framework#103]
LogSink project depends on the IVCT_Conf ENV variable and the IVCT.properties file because it uses the Factory.initialize().

Is this really necessary, or can the LogSink use its own properties file to decouple LogSink from the other components to allow more simple containerized deployment.

**Comment by PHameete** [comment]
Should be solved together with #102

**Comment by rhzg** [comment]
not sure if it is a good idea to have multiple properties files. I would prefer to have only one initialization mechanism in all the JMS clients. 

We need to harmonize the initialization mechanisms in all components.

**Comment by rhzg** [comment]
move all parameters into use environment variables to support docker configuration.
If an application shall be started in native mode, use bat. files to initialize these variables.

**Comment by PHameete** [comment]
While I was working on making a dockerfile for the LogSink I ran into this again. 

Why does the LogSink need the IVCT.Properties. Doesn't it only need to know the activemq host/port and credentials?

**Comment by ducana** [comment]
The property values required by the test system are now done in the following order: environment variables,  IVCT.Properties file then internal default values. The description of these values is found in https://github.com/MSG134/IVCT_Framework/wiki/IVCT_Configuration. Thus the test system can now be run without a IVCT.Properties file: use environment variables instead.
