### ISSUE TITLE
Do LRC libraries need to be bundled with the TestSuites?

### ISSUE THREAD

**Issue by PHameete** [MSG134/IVCT_Framework#108]
The TestSuites are dynamically loaded by the Test Case runner which already has loaded the LRC libraries at runtime.

It seems to be that the LRC libraries don't need to be bundled with the TestSuite distributions as well?

**Comment by rhzg** [comment]
probably not. We will see if the "compileOnly" option in gradle can prevent this.

**Comment by ducana** [comment]
The gradle compileOnly option stops including the RTI LRC in the test suite.
