### ISSUE TITLE
Set up Continuous Integration to automatically build IVCT images

### ISSUE THREAD

**Issue by PHameete** [MSG134/IVCT_Framework#110]
**Step 1: Select a CI solution.**

Options:

- Jenkins
- Travis
- Something else? https://github.com/marketplace/category/continuous-integration

**Step 2: Configure CI to build/test projects and build Docker images)

- Copy files to correct locations
- Write Dockerfiles
- Fix configuration / library linking issues preventing CI

**Comment by rhzg** [comment]
good idea, are you volunteering?

**Comment by PHameete** [comment]
Yes i'll take a look at this part :-)

**Comment by bergtwvd** [comment]
Peter is currently looking at Travis. Input to be provided.

**Comment by bergtwvd** [comment]
Peter has set up Travis and the container images are built automatically.
So this issue can be closed.

**Comment by bergtwvd** [comment]
I re-open the issue to reduce the amount of images built:
* only create an image for the latest version on a branch (master, dev)
* only create an image for defined versions on the master and dev branch

Proposed image naming:
* ``<name>:latest`` (latest master-version)
* ``<name>:<major>.<minor>`` (version on master branch)
* ``<name>:dev-latest`` (latest dev-version)
* ``<name>:dev-<major>.<minor>`` (version on dev branch)

**Comment by PHameete** [comment]
This is changed. No longer building images tagged on commit cash.
