### ISSUE TITLE
Create Wiki pages for identified Docker Images

### ISSUE THREAD

**Issue by rhzg** [MSG134/IVCT_Framework#121]
start with an template for each docker image
use the MSG-164 structure

**Comment by bergtwvd** [comment]
Added information on Container images on the wiki:
* an overview page, with a template for describing images
* several descriptions of images from MSG-164 (Pitch CRC, LRC images)

Additional IVCT images will have to be described as we go along with IVCT version 2.0.

**Comment by bergtwvd** [comment]
Since the basic structure is now in place, I will close this issue.
