### ISSUE TITLE
Exclude slf4j binding from pitch dependencies

### ISSUE THREAD

**Issue by PHameete** [MSG134/IVCT_Framework#132]
TC.exec.gradle and TC.lib.gradle specify a dependency on the rti libraries. This specification should be extended to exclude slf4j bindings.

Pitch LRC 5.4.0.0 has introduced an slf4j binding which conflicts with the binding already present for the IVCT. Having multiple bindings causes an error which prevents the IVCT TC exec from starting.

Relevant error:
```
>SLF4J: Class path contains multiple SLF4J bindings.
>SLF4J: Found binding in [jar:file:/usr/local/pitch/lib/booster1516.jar!/org/slf4j/impl/StaticLoggerBinder.class]
>SLF4J: Found binding in [jar:file:/root/application/TC.exec-1.0.1/lib/logback-classic-1.1.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
>SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
>SLF4J: Actual binding is of type [org.slf4j.impl.JDK14LoggerFactory]
>Exception in thread "main" java.lang.ClassCastException: org.slf4j.impl.JDK14LoggerFactory cannot be cast to ch.qos.logback.classic.LoggerContext
>at de.fraunhofer.iosb.messaginghelpers.LogConfigurationHelper.configureLogging(LogConfigurationHelper.java:40)
>at de.fraunhofer.iosb.testrunner.JMSTestRunner.main(JMSTestRunner.java:65)
>/root/application/start.sh: wait: line 32: Illegal number:
>
```

**Comment by bergtwvd** [comment]
Created a Pitch LRC base image which excludes SLF4J ``StaticLoggerBinder.class`` in ``booster.jar``.

Maybe more class files need to be removed, pending further tests with this image.

Image: ``app-docker136.hex.tno.nl/pitch/lrc:5.4.0.0-alpine-slf4j``

**Comment by bergtwvd** [comment]
Closed with https://github.com/MSG134/IVCT_Framework/issues/128.
