### ISSUE TITLE
GUI: Make badge parameters editable

### ISSUE THREAD

**Issue by bergtwvd** [MSG134/IVCT_Framework#139]
The badge parameters element in the GUI appears to be read-only. Would be nice to have the ability to edit and change the parameter values.

**Comment by rhzg** [comment]
agreed. This is required for release 2.0

**Comment by michaeltheis** [comment]
Work for editing the badge parameters is in progress

**Comment by michaeltheis** [comment]
TC badge parameters can now be edited in development branch version from Dec 10, 2018
