### ISSUE TITLE
GUI: test results lost when switching between test cases

### ISSUE THREAD

**Issue by bergtwvd** [MSG134/IVCT_Framework#140]
When I switch between test cases in the GUI and come back to a one already executed, the test results are gone. Is this intentional? Or should the results be kept until the test case is re-executed.  Preferable the latter.

**Comment by rhzg** [comment]
test is this is still a problem

**Comment by rhzg** [comment]
the UI-tab with the running test should not be closed, while the test case is running. It can not be reopened. If the tab is closed, the test case will continue to run, and it will create a log file. That log file will finally appear in the overview screen of the SuT.

Re-attaching the execution-tab might be an issue for future enhancements. It will not be included in release 2.0
