### ISSUE TITLE
Test suite data in ts-hla-encoding-rules-tester image stored in wrong dir

### ISSUE THREAD

**Issue by bergtwvd** [MSG134/IVCT_Framework#149]
Under Docker the TS data in the ``ts-hla-encoding-rules-tester`` data container is located under ``/root/conf/TestSuites/TS_HLA_EncodingRulesTester``. The runner in the shipsim composition (https://github.com/MSG134/IVCT_Compositions/blob/master/Shipsim/pi-docker-compose.yml) expects the data under ``/root/conf/TestSuites/TS_HLA_EncodingRulesTester-1.0.1``. This is solved in the docker compose file by mounting the volume data in the expected directory.

However, this does not work under Kubernetes, where volume initialisation is done differently w.r.t. Docker. In Kubernetes we need to do volume initialization ourselves using a script in the data container entrypoint:

````
[ "sh", "-c", "if [ -n \"$1\" ]; then cp -r /root/conf/TestSuites/* $1; echo \"Copied data to $1\"; else /bin/true; fi", "--" ]
````

So, in this example, the data ends up at ``/TS_HLA_EncodingRulesTester`` in the data volume. If we then mount this volume at ``/root/conf/TestSuites/TS_HLA_EncodingRulesTester-1.0.1``, then for the runner the data is actually under: ``/root/conf/TestSuites/TS_HLA_EncodingRulesTester-1.0.1/TS_HLA_EncodingRulesTester`` !!

To fix this for the short term, the data directory in the data container should be named ``TS_HLA_EncodingRulesTester-1.0.1`` instead of ``TS_HLA_EncodingRulesTester``.

**Comment by bergtwvd** [comment]
Fix tested for ``msg134/ts-hla-encoding-rules-tester:1.0.1``. Result OK.

Now to do: ``HelloWorld`` and ``msg134/runtime-config:development-latest``. TBC.

**Comment by PHameete** [comment]
This is now pushed as well. But the runtime config adds three folders, and the dockerfile only provides one mount point so I'm not sure if this will go well:

```
ADD IVCT.properties /root/conf/IVCT.properties
ADD IVCTsut /root/conf/IVCTsut
ADD Badges /root/conf/Badges

ENV VOLUMEDIR /root/conf/
ENV VOLUME ${VOLUMEDIR}/.
VOLUME ${VOLUMEDIR}

ENTRYPOINT [ "sh", "-c", "if [ -n \"$1\" ]; then cp -r /root/conf/* $1; echo \"Copied data to $1\"; else /bin/true; fi", "--" ]
```

**Comment by bergtwvd** [comment]
Fixed with the new entrypoint script.
