### ISSUE TITLE
Commit Dockerfile for Encoding tests Test Suite

### ISSUE THREAD

**Issue by bergtwvd** [MSG134/IVCT_Framework#153]
Two things need to happen: 1) Give permission to Peter to push file (to Dev branch), and 2) push Dockerfile.

**Comment by ducana** [comment]
Have added "Framework Developers" team to TS_HLA_EncodingRulesTester with "write" privilege. Peter and Tom are in this team, thus it should be possible now.

**Comment by bergtwvd** [comment]
Ok. Over to Peter now.


Sent from my smartphone.


-------- Original message --------

**Comment by PHameete** [comment]
Pieter* ;-) was able to push. Closing.
