### ISSUE TITLE
LogSink docker images has high CPU consumption

### ISSUE THREAD

**Issue by rhzg** [MSG134/IVCT_Framework#159]
when running the LogSink image, it consumes 100% CPU power. Even when no test case is running.

**Comment by ducana** [comment]
In the case of a Docker image, the stdin.readLine() call delivers a null pointer immediately. The while loop did not do any work and called stdin.readLine() again. This caused a high cpu load. Fixed with a 10s sleep in the loop.

**Comment by bergtwvd** [comment]
I do not think this is a good solution. When LogSink runs in a container it has by default no tty attached, so it should not do a ``stdin.readLine()``.

I propose that you add a command line option that enables the readLine if you want to have that. By default it should not interact with the tty.

**Comment by ducana** [comment]
In the case of a Docker image, the stdin.readLine() call delivers a null pointer immediately. On detection of this null pointer, the program will call a lock and wait indefinitely. The docker will terminate the program when no longer needed.
