### ISSUE TITLE
HLA-BASE test suite running within docker

### ISSUE THREAD

**Issue by rhzg** [MSG134/IVCT_Framework#195]
I'm curently preparing the HLA-BASE test suites to be included into the docker release and encountered the problem, that some of the HLA-BASE tests are using javafx. In the current java VM release openjdk version "1.8.0_111-internal" there is not javafx included. For the moment I just included the jfxrt.jar into the respective test cases - that works, but is propably not the best option (as it may cause conflicts for future version). 

Are there plans to update the LRC images to new java version?

**Comment by bergtwvd** [comment]
Options:

Add general Test Case jars to the container image and classpath of the TC runner. This can be done by adding some logic to the Dockerfile of the TC Runner.

Create a base image for Test Cases, that includes general Test Case jars; these Test Case jars need to be added to the TC runner classpath; probably by adapting the start script of the TC Runner to include these jars in the classpath.

Update JRE version and create new LRC base images (not in the planning at the moment). What JRE version is needed? And is javafx indeed included?  I understood that several jars that are now part of the JRE (8..10) are moved out of the JRE into separate installers (e.g. JAXB). This is to make the JRE footprint smaller. So, there might be more of this in the future.

**Comment by rhzg** [comment]
I have done it as you described as first option. This might not be the final solution, but it works for now
