### ISSUE TITLE
Steps to run the TS_HelloWorld?

### ISSUE THREAD

**Issue by jaffguo** [MSG134/IVCT_Framework#25]
Question: I'm new to the TC development. I tried to use the "gradlew run" command to run the TS_HelloWorld from a Windows Command Prompt with an "activemq start" command in another Windows Command Prompt. the last line displayed was “> Building 44% > :TS_HelloWorld:run”. Is this display correct? How could I know the TS_HelloWorld is working properly without using a web browser?
Thanks,

jaff

**Comment by ManfredSchenkIOSB** [comment]
The TS_HelloWorld uses the JMSTestRunner to run the tests. So you have to trigger the execution of the test by sending an appropriate JMS Message via activeMQ. The "gradlew run" command just compiles the project and starts the JMSTestRunner which is then waiting for incoming JMS messages.

**Comment by jaffguo** [comment]
I very much appreciate your help. I tried to run the tests with JMSTestRunner.  My steps were as follows: (1) run “activemq start” in a command line window, (2) run “TC” in another command line window, (3) log in http://localhost:8161/admin, and click “Send To” a  “commands” with the text: “de.fraunhof.iosb.tc_helloworld.TC0001”. (4) Exception displayed in the TC commandl ine window: “Could not instantiate de.fraunhof.iosb.tc_helloworld.TC0001 !”, ClassNotFoundException: de.graunhof.iosob.tc_helloworld.TC0001”. 
Would the steps above are a correct way to execute a test case? If not, what are correct steps? If yes, there are more details with more attempts as follows:
Attempt1: Using the TC.bat with http://localhost:8161/admin: i.e. Adding the TS_HelloWorld-0.0.1.jar with its absolute path to the line - “set CLASSPATH=…” in the TC.bat file, the error msg was the same.
Attempte2: Using the TC.bat with http://localhost:8161/admin:  i.e.  adding  the “–Classpath %CLASSPATH%;” plus TS_HelloWorld-0.0.1.jar and its absolute path to TC.bat command line:  the error msg was the same.
Attempt3: Using the TC.bat to start TC0001 without the http://localhost:6161/admin: i.e. using TC.bat with the “–Classpath %CLASSPATH%;” plus TS_HelloWorld-0.0.1.jar and its absolute path, and plus “-jar de.fraunhof.iosb.tc_helloworld.TC0001”, then no error displayed in the TC command line window and no log message was found. I would be very grateful, if you could provide more help.
Thanks,
jaff

**Comment by ducana** [comment]
Before we go any further, I have a question: when did you download the sources?  Please let me know which version you have. I placed a new version onto GitHub last Friday (18th of March) which is not compatible with the previous run instructions. The new version has a primitive UI in a command window to run individual or sequences of test cases. The description for the new version is in https://github.com/MSG134/IVCT_Framework/wiki/commandlinetool.The old description is in https://github.com/MSG134/IVCT_Framework/wiki/jmstestrunner.

**Comment by jaffguo** [comment]
I checked the version I downloaded. It came from the master branch committed  3 months ago, and the development branch is newer. I'm going to download the development branch and try it again.
Thanks,
jaff

**Comment by ducana** [comment]
That is the best way to go, since the new UI should make development and testing of test cases easier. I have not received any feedback from anyone else since last week. Thus you will be one of the first to try it out. If there are any problems, I can give you support today and then again on Tuesday next week (Easter Monday is a holiday here).
