### ISSUE TITLE
Why creating TS Run Folder?

### ISSUE THREAD

**Issue by rmauget** [MSG134/IVCT_Framework#40]
In the private class named `onMessageConsumer` declared in `JMSTestRunner` class, in the setCurrentDirectory() method, why trying to create the directory (`directory.mkdirs()`) if the directory does not exist? 
If it does not exit, isn’t it an error?
Indeed, that directory must contain configuration file(s) required for the execution of the TC.

**Comment by ducana** [comment]
Java does not provide a direct way to set current working directory, so this method was written to provide the same effect. There was a fault in the logic that would create a non-existing path with the given pathname. The logic has been fixed to only call "directory.mkdirs()" only if existing (This seems strange, but it works nicely!).
