### ISSUE TITLE
ivct_BaseModel.terminateRti() call in catch blocks

### ISSUE THREAD

**Issue by rmauget** [MSG134/IVCT_Framework#41]
In the `AbstractTestCase` class, in the `execute()` method, in several catch blocks, there is a call to `ivct_BaseModel.terminateRti();` without verifying that `ivct_BaseModel` is not null. That may be the case if no connection to RTI is required by the TC (for instance, TC CS VERIFICATION does not connect to RTI, because it only checks files).
May that code be replaced by:
```
If (ivct_BaseModel != null) { 
    ivct_BaseModel.terminateRti();
}
```

**Comment by ducana** [comment]
The code has been fixed as suggested.
