### ISSUE TITLE
Empty catch block in execute() of AbstractTestCase 

### ISSUE THREAD

**Issue by rmauget** [MSG134/IVCT_Framework#42]
The `AbstractTestCase` class contains the following source code:
```
public IVCT_Verdict execute(final String tcParamJson, final Logger logger) {
               
               IVCT_BaseModel ivct_BaseModel = null;
               IVCT_Verdict ivct_Verdict = new IVCT_Verdict();
               
               try {
                              ivct_BaseModel = getIVCT_BaseModel(tcParamJson, logger);
               } catch (TcInconclusive e) {
               }
```
When there is a problem while calling `getIVCT_BaseModel()`, no error message is logged because the catch section is empty. So the user is not informed that there is an error.

Is it possible to log an error?

**Comment by ducana** [comment]
The catch block has been changed to log a message as suggested. A number of similar catch blocks have been fixed in other parts of the test system.
