### ISSUE TITLE
Change log level from INFO to DEBUG for IVCT_RTIambassador

### ISSUE THREAD

**Issue by rmauget** [MSG134/IVCT_Framework#51]
In order to avoid too many logs in INFO mode, change the level of log in class `de.fraunhofer.iosb.tc_lib.IVCT_RTIambassador ` from INFO to DEBUG.
So, replace all` logger.info()` by `logger.debug()`.
For instance, ETC FRA use a lot of RTI services, so, in INFO mode, there is currently too many traces.
RTI services calls have to be considered as DEBUG level information.

**Comment by rhzg** [comment]
I agree that INFO log-level for the RTI library functions is not the best choice. However, the DEBUG level should be reserved for non-permanent messages only to be used for debugging purpose and should not be included in any release version. My proposal is use the following classification:

- FATAL: non recoverable error forcing a system shutdown. Only the framework should generate such
messages (something like disc or network failure)

- ERROR: Any error which is fatal to the operation, but not the service or application (can't open a required file, missing data, etc.). These errors will require direct user (administrator, or direct user) intervention.

- WARN: Anything which is not normal, but can be handled by the service without aborting the operation. But the user should be informed and may be required to react eventually.

- INFO: General useful information about the program logic. Typically high level information like test case purpose and test results. Overview information on the test case execution steps, or on the tested interoperability requirements, may also be provided as info.

- TRACE: Detailed information about the program or test case execution sequence. Typically to be used for trouble shooting or interoperability issue analysis 

- DEBUG: Any program message used by developers during debugging session. May not be used systematically and shall not be included in the released code. 

Following that categorization the HLA-Interface messages should be classified as TRACE messages and anything that describes the test case logic should be classified as INFO.

What do you think about that?

**Comment by rmauget** [comment]
I fully agree with that proposal. So, could you please:

- Change the level of log in class  de.fraunhofer.iosb.tc_lib.IVCT_RTIambassador  from INFO to TRACE

- Create  a specific chapter on log level to use for test case development in the dedicated Wiki page: [https://github.com/MSG134/IVCT_Framework/wiki/TcDevelGuide](url)

**Comment by rmauget** [comment]
I have closed that issue but ... is it OK for everybody?
