### ISSUE TITLE
Use environment variable JAVA_OPTS when starting JMSTestRunner

### ISSUE THREAD

**Issue by rmauget** [MSG134/IVCT_Framework#52]
Some ETC uses some values in` JAVA_OPTS` environment variable to be configured.
For instance, ETC FRA uses the following values to be configured in English language:
`set JAVA_OPTS=-Duser.country=US -Duser.language=EN`
And the following values to be configured in French language:
`set JAVA_OPTS=-Duser.country=FR -Duser.language=FR`

So, it requires `JAVA_OPTS` environment variable to be passed as an argument when starting JMSTestRunner.
To do so, in class `TcRunnable` defined in class `de.fraunhofer.iosb.ivct.CmdLineTool`, replace:
```
System.out.println("\"" + javaExe + "\" -classpath \"" + classPath + "\" de.fraunhofer.iosb.testrunner.JMSTestRunner");
CmdLineTool.p = Runtime.getRuntime().exec("\"" + javaExe + "\" -classpath \"" + classPath + "\" de.fraunhofer.iosb.testrunner.JMSTestRunner", null, f);
```
with:
```
String javaOpts = System.getenv("JAVA_OPTS");
System.out.println("\"" + javaExe + "\" " + javaOpts +" -classpath \"" + classPath + "\" de.fraunhofer.iosb.testrunner.JMSTestRunner");
CmdLineTool.p = Runtime.getRuntime().exec("\"" + javaExe + "\" " + javaOpts + " -classpath \"" + classPath + "\" de.fraunhofer.iosb.testrunner.JMSTestRunner", null, f);
```

**Comment by ducana** [comment]
The suggested code has been implemented in the CmdLineTool.
