### ISSUE TITLE
Use JAVA's File.separator instead of hardcoded '\\

### ISSUE THREAD

**Issue by PHameete** [MSG134/IVCT_Framework#58]
Throughout the codebase I often found that '\\' is being used as a file separator in paths. This only works for Windows however. 

By replacing this with Java's 'File.separator' constant the paths will work on both Linux and Windows. This is important for containerization.

**Comment by rhzg** [comment]
You are right - we will fix that

**Comment by PHameete** [comment]
Cheers Reinhard, for your quick responses :-)

If I have the time I will try to fix such issues myself via pull request. Unfortunately I'll be gone for the next few weeks. It's also a bit more time-consuming to do it via a fork.
