### ISSUE TITLE
Run IVCT with predetermined set of commands

### ISSUE THREAD

**Issue by PHameete** [MSG134/IVCT_Framework#64]
Currently, the IVCT can be run using the CmdLineTool which waits for user commands to execute until the IVCT is terminated.

Is it possible to also run the IVCT with a predetermined set of commands (for example provided via parameters upon startup) and terminate after completion? For example: select test suite TS_xxxx, execute test schedule TS_yyyy against SuT zzzz, and then shut down the IVCT.

**Comment by rhzg** [comment]
The ICVT architecture forsees a scheduling component for that purpose. The current CmdLineTool is only a placeholder implementation for that. The problem here is the our current test cases are requiring interactive configuration actions within the system under test, and for that reason the scheduling component was not high on our todo list

**Comment by PHameete** [comment]
Hi Reinhard,

great to hear that you were already thinking about this. A scheduling component seems like a good solution for this. Did you already discuss how such a scheduling component should work? I would be interested in finding out more about it.

If theres anything we can do to help please let me know. I think this component would have a lot of value with respect to offering the IVCT as an (automated) service.

**Comment by rhzg** [comment]
Our first idea was to use something like BPMN to specific test case schedules. But then we figure this might me an overkill solution and we reduced the idea to a simple sequence of test cases issued by the start test case command provider (UI and GUI). I guess we need something in the middle in terms of complexity. For sure we will need parallel execution of observer-type test cases. 

The main problem with automation will be the SuT operator part. For that we are planing to have a SuT-Operator-federate with synchronization capability between the test cases and the SuT.
