### ISSUE TITLE
Dynamic testcase parameters

### ISSUE THREAD

**Issue by ducana** [MSG134/IVCT_Framework#83]
The test operator may want to run a testcase with various dynamic parameters to control the running of the testcase. For example, some testcases are purely observer testcases and evaluate the SUT values for an indeterminate length of time: the test operator may want to specify the length of time the testcase should run. Such parameters should appear in the test report to qualify the test verdict.

**Comment by rhzg** [comment]
the GUI allows the editing of the TC.param
