### ISSUE TITLE
GUI project is not a gradle but a Maven project

### ISSUE THREAD

**Issue by PHameete** [MSG134/IVCT_Framework#98]
The GUI project is not a gradle project, but a maven project. This has the following implications:

- Running `gradle eclipse` in the IVCT_Framework root folder won't create project files for the GUI projects
- The GUI projects need to be imported separately as Maven projects

I believe it would be preferable to have all projects use the same project management / build tool, so to convert the Maven config for the GUI project to gradle as well.

**Comment by rhzg** [comment]
in the latest development branch there is no more mvn build inluded. This issue should be solved. We will test again.

**Comment by ducana** [comment]
The development branch was compiled using gradle (without maven). The eclipse projects can be loaded and used without errors. The GUI can be started and used.
