### ISSUE TITLE
nato.ivct.gui.shared generated classes folder not included as a source dir

### ISSUE THREAD

**Issue by PHameete** [MSG134/IVCT_Framework#99]
nato.ivct.gui.shared /src/generated/java directory is not marked as a source directory. This causes the corresponding classes not to be compiled by Eclipse, and the depending projects will have missing classes.

Resolution should be to configure the pom.xml (or gradle config after handling #98) to include the /src/generated/java folder as source dir.

**Comment by rhzg** [comment]
this should be solved along with #98

**Comment by rhzg** [comment]
This should be solved with the gradle command 
```
sourceSets.main.java.srcDirs += 'src/generated/java'
```
this seems to work with the "grade eclipse" tools. Which IDE are you using?

**Comment by PHameete** [comment]
Eclipse, but I wasn't working on the development branch yet so I'll try later :-)

**Comment by ducana** [comment]
This was fixed by michaeltheis on April 16th 2018 and merged on the development branch.
